/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthAuthImport } from './routes/_auth/auth_'
import { Route as AppMeImport } from './routes/_app/me_'
import { Route as AppMatchImport } from './routes/_app/match'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppHistoryImport } from './routes/_app/history'
import { Route as AuthAuthRegisterImport } from './routes/_auth/auth.register'
import { Route as AuthAuthLoginImport } from './routes/_auth/auth.login'
import { Route as AuthAuthForgottenpasswordImport } from './routes/_auth/auth.forgottenpassword'
import { Route as AppProfileUsernameImport } from './routes/_app/profile.$username'
import { Route as AppMeProfileImport } from './routes/_app/me.profile'
import { Route as AppMeEditInfoImport } from './routes/_app/me.edit-info'
import { Route as AppMeEditImagesImport } from './routes/_app/me.edit-images'
import { Route as AuthAuthVerifyIdImport } from './routes/_auth/auth.verify.$id'
import { Route as AuthAuthResetpasswordIdImport } from './routes/_auth/auth.resetpassword.$id'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/auth_',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)

const AppMeRoute = AppMeImport.update({
  id: '/me_',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)

const AppMatchRoute = AppMatchImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppHistoryRoute = AppHistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthForgottenpasswordRoute = AuthAuthForgottenpasswordImport.update({
  id: '/auth/forgottenpassword',
  path: '/auth/forgottenpassword',
  getParentRoute: () => AuthRoute,
} as any)

const AppProfileUsernameRoute = AppProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)

const AppMeProfileRoute = AppMeProfileImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AppRoute,
} as any)

const AppMeEditInfoRoute = AppMeEditInfoImport.update({
  id: '/me/edit-info',
  path: '/me/edit-info',
  getParentRoute: () => AppRoute,
} as any)

const AppMeEditImagesRoute = AppMeEditImagesImport.update({
  id: '/me/edit-images',
  path: '/me/edit-images',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthVerifyIdRoute = AuthAuthVerifyIdImport.update({
  id: '/auth/verify/$id',
  path: '/auth/verify/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthResetpasswordIdRoute = AuthAuthResetpasswordIdImport.update({
  id: '/auth/resetpassword/$id',
  path: '/auth/resetpassword/$id',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryImport
      parentRoute: typeof AppImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchImport
      parentRoute: typeof AppImport
    }
    '/_app/me_': {
      id: '/_app/me_'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeImport
      parentRoute: typeof AppImport
    }
    '/_auth/auth_': {
      id: '/_auth/auth_'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthImport
    }
    '/_app/me/edit-images': {
      id: '/_app/me/edit-images'
      path: '/me/edit-images'
      fullPath: '/me/edit-images'
      preLoaderRoute: typeof AppMeEditImagesImport
      parentRoute: typeof AppImport
    }
    '/_app/me/edit-info': {
      id: '/_app/me/edit-info'
      path: '/me/edit-info'
      fullPath: '/me/edit-info'
      preLoaderRoute: typeof AppMeEditInfoImport
      parentRoute: typeof AppImport
    }
    '/_app/me/profile': {
      id: '/_app/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AppMeProfileImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameImport
      parentRoute: typeof AppImport
    }
    '/_auth/auth/forgottenpassword': {
      id: '/_auth/auth/forgottenpassword'
      path: '/auth/forgottenpassword'
      fullPath: '/auth/forgottenpassword'
      preLoaderRoute: typeof AuthAuthForgottenpasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/resetpassword/$id': {
      id: '/_auth/auth/resetpassword/$id'
      path: '/auth/resetpassword/$id'
      fullPath: '/auth/resetpassword/$id'
      preLoaderRoute: typeof AuthAuthResetpasswordIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/verify/$id': {
      id: '/_auth/auth/verify/$id'
      path: '/auth/verify/$id'
      fullPath: '/auth/verify/$id'
      preLoaderRoute: typeof AuthAuthVerifyIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMatchRoute: typeof AppMatchRoute
  AppMeRoute: typeof AppMeRoute
  AppMeEditImagesRoute: typeof AppMeEditImagesRoute
  AppMeEditInfoRoute: typeof AppMeEditInfoRoute
  AppMeProfileRoute: typeof AppMeProfileRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppMatchRoute: AppMatchRoute,
  AppMeRoute: AppMeRoute,
  AppMeEditImagesRoute: AppMeEditImagesRoute,
  AppMeEditInfoRoute: AppMeEditInfoRoute,
  AppMeProfileRoute: AppMeProfileRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthAuthForgottenpasswordRoute: typeof AuthAuthForgottenpasswordRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
  AuthAuthResetpasswordIdRoute: typeof AuthAuthResetpasswordIdRoute
  AuthAuthVerifyIdRoute: typeof AuthAuthVerifyIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthAuthForgottenpasswordRoute: AuthAuthForgottenpasswordRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
  AuthAuthResetpasswordIdRoute: AuthAuthResetpasswordIdRoute,
  AuthAuthVerifyIdRoute: AuthAuthVerifyIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/match': typeof AppMatchRoute
  '/me': typeof AppMeRoute
  '/auth': typeof AuthAuthRoute
  '/me/edit-images': typeof AppMeEditImagesRoute
  '/me/edit-info': typeof AppMeEditInfoRoute
  '/me/profile': typeof AppMeProfileRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/auth/forgottenpassword': typeof AuthAuthForgottenpasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/resetpassword/$id': typeof AuthAuthResetpasswordIdRoute
  '/auth/verify/$id': typeof AuthAuthVerifyIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/match': typeof AppMatchRoute
  '/me': typeof AppMeRoute
  '/auth': typeof AuthAuthRoute
  '/me/edit-images': typeof AppMeEditImagesRoute
  '/me/edit-info': typeof AppMeEditInfoRoute
  '/me/profile': typeof AppMeProfileRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/auth/forgottenpassword': typeof AuthAuthForgottenpasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/resetpassword/$id': typeof AuthAuthResetpasswordIdRoute
  '/auth/verify/$id': typeof AuthAuthVerifyIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/match': typeof AppMatchRoute
  '/_app/me_': typeof AppMeRoute
  '/_auth/auth_': typeof AuthAuthRoute
  '/_app/me/edit-images': typeof AppMeEditImagesRoute
  '/_app/me/edit-info': typeof AppMeEditInfoRoute
  '/_app/me/profile': typeof AppMeProfileRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_auth/auth/forgottenpassword': typeof AuthAuthForgottenpasswordRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_auth/auth/resetpassword/$id': typeof AuthAuthResetpasswordIdRoute
  '/_auth/auth/verify/$id': typeof AuthAuthVerifyIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/history'
    | '/home'
    | '/match'
    | '/me'
    | '/auth'
    | '/me/edit-images'
    | '/me/edit-info'
    | '/me/profile'
    | '/profile/$username'
    | '/auth/forgottenpassword'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resetpassword/$id'
    | '/auth/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/history'
    | '/home'
    | '/match'
    | '/me'
    | '/auth'
    | '/me/edit-images'
    | '/me/edit-info'
    | '/me/profile'
    | '/profile/$username'
    | '/auth/forgottenpassword'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resetpassword/$id'
    | '/auth/verify/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/history'
    | '/_app/home'
    | '/_app/match'
    | '/_app/me_'
    | '/_auth/auth_'
    | '/_app/me/edit-images'
    | '/_app/me/edit-info'
    | '/_app/me/profile'
    | '/_app/profile/$username'
    | '/_auth/auth/forgottenpassword'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_auth/auth/resetpassword/$id'
    | '/_auth/auth/verify/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/history",
        "/_app/home",
        "/_app/match",
        "/_app/me_",
        "/_app/me/edit-images",
        "/_app/me/edit-info",
        "/_app/me/profile",
        "/_app/profile/$username"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth_",
        "/_auth/auth/forgottenpassword",
        "/_auth/auth/login",
        "/_auth/auth/register",
        "/_auth/auth/resetpassword/$id",
        "/_auth/auth/verify/$id"
      ]
    },
    "/_app/history": {
      "filePath": "_app/history.tsx",
      "parent": "/_app"
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_app/match": {
      "filePath": "_app/match.tsx",
      "parent": "/_app"
    },
    "/_app/me_": {
      "filePath": "_app/me_.tsx",
      "parent": "/_app"
    },
    "/_auth/auth_": {
      "filePath": "_auth/auth_.tsx",
      "parent": "/_auth"
    },
    "/_app/me/edit-images": {
      "filePath": "_app/me.edit-images.tsx",
      "parent": "/_app"
    },
    "/_app/me/edit-info": {
      "filePath": "_app/me.edit-info.tsx",
      "parent": "/_app"
    },
    "/_app/me/profile": {
      "filePath": "_app/me.profile.tsx",
      "parent": "/_app"
    },
    "/_app/profile/$username": {
      "filePath": "_app/profile.$username.tsx",
      "parent": "/_app"
    },
    "/_auth/auth/forgottenpassword": {
      "filePath": "_auth/auth.forgottenpassword.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/login": {
      "filePath": "_auth/auth.login.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/register": {
      "filePath": "_auth/auth.register.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/resetpassword/$id": {
      "filePath": "_auth/auth.resetpassword.$id.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/verify/$id": {
      "filePath": "_auth/auth.verify.$id.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
